server:
  port: 4000
spring:
  application:
    name: client-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:4001/eureka/}